# Generated by Django 4.2.7 on 2025-07-22 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QuickAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "prompt_template",
                    models.TextField(
                        help_text="Template for the prompt that will be sent to AI"
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="fas fa-question-circle",
                        help_text="FontAwesome icon class",
                        max_length=50,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("study", "Study Help"),
                            ("math", "Mathematics"),
                            ("science", "Science"),
                            ("language", "Language Arts"),
                            ("general", "General"),
                        ],
                        default="general",
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("usage_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-usage_count", "title"],
            },
        ),
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(default="New Chat Session", max_length=255)),
                (
                    "session_type",
                    models.CharField(
                        choices=[
                            ("study_help", "Study Help"),
                            ("quiz_explanation", "Quiz Explanation"),
                            ("general", "General Chat"),
                            ("homework_help", "Homework Help"),
                            ("concept_help", "Concept Help"),
                        ],
                        default="general",
                        max_length=25,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatbotSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "preferred_ai_provider",
                    models.CharField(
                        choices=[
                            ("openai", "OpenAI GPT"),
                            ("gemini", "Google Gemini"),
                            ("perplexity", "Perplexity AI"),
                        ],
                        default="perplexity",
                        max_length=20,
                    ),
                ),
                (
                    "response_style",
                    models.CharField(
                        choices=[
                            ("formal", "Formal"),
                            ("casual", "Casual"),
                            ("detailed", "Detailed"),
                            ("concise", "Concise"),
                        ],
                        default="casual",
                        max_length=20,
                    ),
                ),
                (
                    "enable_web_search",
                    models.BooleanField(
                        default=True,
                        help_text="Enable real-time web search for responses",
                    ),
                ),
                (
                    "enable_citations",
                    models.BooleanField(
                        default=True, help_text="Include source citations in responses"
                    ),
                ),
                (
                    "max_context_messages",
                    models.IntegerField(
                        default=10,
                        help_text="Number of previous messages to include as context",
                    ),
                ),
                (
                    "auto_suggest_questions",
                    models.BooleanField(
                        default=True,
                        help_text="Automatically suggest follow-up questions",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chatbot_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Chatbot Settings",
                "verbose_name_plural": "Chatbot Settings",
            },
        ),
        migrations.CreateModel(
            name="BotMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[("user", "User Message"), ("bot", "Bot Response")],
                        max_length=10,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "ai_provider",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("openai", "OpenAI GPT"),
                            ("gemini", "Google Gemini"),
                            ("perplexity", "Perplexity AI"),
                            ("fallback", "Fallback Response"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "response_time",
                    models.FloatField(
                        blank=True, help_text="Response time in seconds", null=True
                    ),
                ),
                ("tokens_used", models.IntegerField(blank=True, null=True)),
                (
                    "is_helpful",
                    models.BooleanField(
                        blank=True, help_text="User feedback on bot response", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chatbot.chatsession",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
