# Generated by Django 4.2.7 on 2025-07-22 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField()),
                (
                    "achievement_type",
                    models.CharField(
                        choices=[
                            ("quiz_master", "Quiz Master"),
                            ("streak_keeper", "Streak Keeper"),
                            ("social_butterfly", "Social Butterfly"),
                            ("perfectionist", "Perfectionist"),
                            ("speed_demon", "Speed Demon"),
                            ("knowledge_seeker", "Knowledge Seeker"),
                            ("mentor", "Mentor"),
                            ("challenger", "Challenger"),
                        ],
                        max_length=20,
                    ),
                ),
                ("icon", models.CharField(default="fas fa-trophy", max_length=50)),
                ("color", models.CharField(default="#FFD700", max_length=7)),
                ("points", models.IntegerField(default=10)),
                ("is_rare", models.BooleanField(default=False)),
                (
                    "requirements",
                    models.JSONField(
                        default=dict,
                        help_text="Achievement requirements in JSON format",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bio_extended",
                    models.TextField(
                        blank=True,
                        help_text="Extended bio for social profile",
                        max_length=1000,
                    ),
                ),
                ("website_url", models.URLField(blank=True)),
                ("location", models.CharField(blank=True, max_length=100)),
                ("posts_count", models.IntegerField(default=0)),
                ("likes_received", models.IntegerField(default=0)),
                ("shares_count", models.IntegerField(default=0)),
                ("show_email", models.BooleanField(default=False)),
                ("show_quiz_history", models.BooleanField(default=True)),
                ("show_followers", models.BooleanField(default=True)),
                ("show_following", models.BooleanField(default=True)),
                ("allow_messages", models.BooleanField(default=True)),
                ("notify_on_follow", models.BooleanField(default=True)),
                ("notify_on_quiz_share", models.BooleanField(default=True)),
                ("notify_on_mention", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SocialNotification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("follow", "New Follower"),
                            ("unfollow", "Unfollowed"),
                            ("quiz_shared", "Quiz Shared"),
                            ("achievement", "Achievement Unlocked"),
                            ("mention", "Mentioned"),
                            ("quiz_challenge", "Quiz Challenge"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("related_quiz_id", models.CharField(blank=True, max_length=100)),
                ("related_url", models.URLField(blank=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SocialFeed",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("quiz_completed", "Quiz Completed"),
                            ("quiz_shared", "Quiz Shared"),
                            ("achievement_earned", "Achievement Earned"),
                            ("user_followed", "User Followed"),
                            ("quiz_created", "Quiz Created"),
                            ("milestone_reached", "Milestone Reached"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("metadata", models.JSONField(default=dict)),
                ("is_public", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feed_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QuizShare",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("quiz_id", models.CharField(max_length=100)),
                ("quiz_title", models.CharField(max_length=200)),
                ("share_message", models.TextField(blank=True, max_length=500)),
                ("is_public", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "shared_with",
                    models.ManyToManyField(
                        blank=True,
                        related_name="received_quiz_shares",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_shares",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserInteraction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "interaction_type",
                    models.CharField(
                        choices=[
                            ("like", "Like"),
                            ("share", "Share"),
                            ("comment", "Comment"),
                            ("bookmark", "Bookmark"),
                        ],
                        max_length=20,
                    ),
                ),
                ("target_type", models.CharField(max_length=50)),
                ("target_id", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "target_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_interactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {
                    ("user", "target_type", "target_id", "interaction_type")
                },
            },
        ),
        migrations.CreateModel(
            name="UserAchievement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("earned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "progress",
                    models.JSONField(default=dict, help_text="Progress tracking data"),
                ),
                (
                    "is_displayed",
                    models.BooleanField(default=True, help_text="Show on profile"),
                ),
                (
                    "achievement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="social.achievement",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="achievements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-earned_at"],
                "unique_together": {("user", "achievement")},
            },
        ),
        migrations.CreateModel(
            name="Follow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "followed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "follower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="following",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("follower", "followed")},
            },
        ),
    ]
